GET http://localhost:8000/all-movies

###

GET http://localhost:8000/filmes

###

GET http://localhost:8000/completed-tasks


###


POST http://localhost:8000/create-movie
Content-Type: application/json

{

   "titulo": "Carros 2",
   "genero": "Corrida",
   "duracao": "105 ",
   "ClassificacaoEtaria": "Livre"

}


###


DELETE http://localhost:8000/delete-task/11

