GET http://localhost:6666/all-tasks

###

GET http://localhost:6666/filmes

###

GET http://localhost:6666/completed-tasks


###


POST http://localhost:6666/create-movie
Content-Type: application/json

{

   "titulo": "Velozes e Furiosos 2",
   "genero": "Ação",
   "duracao": "107 ",
   "ClassificacaoEtaria": "14 anos"

}


###


DELETE http://localhost:6666/delete-task/11

