GET http://localhost:6666/all-tasks

###

GET http://localhost:6666/filmes

###

GET http://localhost:6666/completed-tasks


###


POST http://localhost:6666/create-movie
Content-Type: application/json

{

   "titulo": "Carros 2",
   "genero": "Corrida",
   "duracao": "105 ",
   "ClassificacaoEtaria": "Livre"

}


###


DELETE http://localhost:6666/delete-task/11

